CREATE TABLE products (
    ID UUID PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(20, 2) NOT NULL,
    STOCK INTEGER NOT NULL DEFAULT 0,
    IMAGES_URL TEXT[] NOT NULL,
    SLUG VARCHAR(255) UNIQUE NOT NULL,
    CATEGORY_ID UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_price_positive CHECK (PRICE >= 0),
    CONSTRAINT chk_stock_positive CHECK (STOCK >= 0)

);