CREATE TYPE order_status_enum AS ENUM ('PROCESSING', 'APPROVED', 'CANCELED');

CREATE TABLE orders (
    ID UUID PRIMARY KEY NOT NULL,
    TOTAL DECIMAL(10,2) NOT NULL,
    STATUS order_status_enum NOT NULL,
    CUSTOMER_ID UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);